/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Lottery__factory } from "./Lottery__factory";
export { MyERC20__factory } from "./MyERC20__factory";
